GET http://localhost:8000/users

###
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "username": "sweetMango",
    "password": "XCM2345",
    "email": "sweetMango132@gmail.com"
}

###
DELETE http://localhost:8000/users/9 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "username": "random",
    "password": "dsfas.12.02",
    "email": "randomuser@gmail.com"
}

####
POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "email":"spirosGats@gmail.com",
    "password":"27.01.2002"
}